using System;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.Extensions.Logging;

namespace $rootnamespace$
{

/// <summary>
/// Generated by the mediatorHandler Template.
/// </summary>


public class $safeitemname$ : IRequestHandler<$userinput$Request, $userinput$Response>
{
private ILogger<$safeitemname$> _logger;
public $safeitemname$(ILogger<$safeitemname$> logger)
{
    _logger = logger;
}

public Task<$userinput$Response> Handle($userinput$Request request, CancellationToken cancellationToken)
{
    throw new NotImplementedException();
}
} 
}