using System;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.Extensions.Logging;

namespace $rootnamespace$
{

/// <summary>
/// Generated by the mediatorHandler Template.
/// </summary>

public class $safeitemname$
{

}
}